# generated by fastapi-codegen:
#   filename:  openapi.yaml
#   timestamp: 2025-06-28T18:31:14+00:00



import argparse
import json
import os
from typing import *
from typing import Any, Optional, Union

from autogen.mcp.mcp_proxy import MCPProxy
from autogen.mcp.mcp_proxy.security import (
    APIKeyHeader,
    BaseSecurity,
    HTTPBearer,
    UnsuportedSecurityStub,
)
from fastapi import Query, Request, UploadFile
from starlette.requests import Request

from models import (
    AccessResponse,
    Account1PushuriPostResponse,
    Account1PushuriPostResponse1,
    Account1PushuriPostResponse2,
    Account1PushuriPostResponse3,
    Account2VerifyPostResponse,
    Account2VerifyPostResponse1,
    Account2VerifyPostResponse2,
    CodeChallenge1,
    CodeChallengeMethod1,
    DemoAuthResponse,
    DemoAuthVerifyResponse,
    DeviceAuthorizationCode,
    DeviceAuthorizationCodeResponse,
    DocTypeResponse,
    EaadharXamlSchema,
    FileUploadResponse,
    GetStatisticsResponse,
    IssuerResponse,
    Oauth21AuthorizeGetResponse,
    Oauth21CodePostResponse,
    Oauth21CodePostResponse1,
    Oauth21CodePostResponse2,
    Oauth21FilesGetResponse,
    Oauth21FilesGetResponse1,
    Oauth21FilesGetResponse2,
    Oauth21FilesGetResponse3,
    Oauth21FilesIdGetResponse,
    Oauth21FilesIdGetResponse1,
    Oauth21FilesIdGetResponse2,
    Oauth21FilesIdGetResponse3,
    Oauth21FilesIssuedGetResponse,
    Oauth21FilesIssuedGetResponse1,
    Oauth21FilesIssuedGetResponse2,
    Oauth21FileUploadPostResponse,
    Oauth21FileUploadPostResponse1,
    Oauth21FileUploadPostResponse2,
    Oauth21FileUriGetResponse,
    Oauth21FileUriGetResponse1,
    Oauth21FileUriGetResponse2,
    Oauth21FileUriGetResponse3,
    Oauth21FileUriGetResponse4,
    Oauth21PullDoctypePostResponse,
    Oauth21PullDoctypePostResponse1,
    Oauth21PullDoctypePostResponse2,
    Oauth21PullIssuersPostResponse,
    Oauth21PullIssuersPostResponse1,
    Oauth21PullIssuersPostResponse2,
    Oauth21PullParametersPostResponse,
    Oauth21PullParametersPostResponse1,
    Oauth21PullParametersPostResponse2,
    Oauth21PullPulldocumentPostResponse,
    Oauth21PullPulldocumentPostResponse1,
    Oauth21PullPulldocumentPostResponse2,
    Oauth21PullPulldocumentPostResponse3,
    Oauth21PullPulldocumentPostResponse4,
    Oauth21RevokePostRequest,
    Oauth21TokenPostRequest,
    Oauth21UserGetResponse,
    Oauth21UserGetResponse1,
    Oauth21UserGetResponse2,
    Oauth21XmlUriGetResponse,
    Oauth21XmlUriGetResponse1,
    Oauth21XmlUriGetResponse2,
    Oauth21XmlUriGetResponse3,
    Oauth21XmlUriGetResponse4,
    Oauth22FilesIssuedGetResponse,
    Oauth22FilesIssuedGetResponse1,
    Oauth22FilesIssuedGetResponse2,
    Oauth22XmlEaadhaarGetResponse,
    Oauth22XmlEaadhaarGetResponse1,
    Oauth22XmlEaadhaarGetResponse2,
    Oauth22XmlEaadhaarGetResponse3,
    SearchParametersResponse,
    Signup1DemoauthverifyPostResponse,
    Signup1DemoauthverifyPostResponse1,
    Signup1DemoauthverifyPostResponse2,
    Signup2DemoauthPostResponse,
    Signup2DemoauthPostResponse1,
    Signup2DemoauthPostResponse2,
    Statistics1CountsPostResponse,
    Statistics1CountsPostResponse1,
    Statistics1CountsPostResponse2,
    VerifyAccountResponse,
    XMLFormatSchema,
)

app = MCPProxy(
    contact={'email': 'support@digitallocker.gov.in'},
    description='To access files in user’s DigiLocker account from your application, you must first obtain user’s authorization.',
    termsOfService='https://ndh.digitallocker.gov.in/terms.php',
    title='Authorized Partner API Specification',
    version='1.0.0',
    servers=[{'url': 'https://betaapi.digitallocker.gov.in/public'}],
)


@app.post(
    '/account/1/pushuri',
    description=""" The API can use to push or delete a single URI into Digital Locker using DigiLocker Id acquired using Get User Details API. This API can be used to push the certificate details to Digital Locker as and when a certificate is generated in the issuer system. The issuing departments must register on DigiLocker as a registered Issuer and implement the requisite Issuer APIs as mentioned in Digital Locker Issuer API Specification document prior to pushing certificates using this API. """,
    tags=['file_operations'],
    security=[
        UnsuportedSecurityStub(name="None"),
    ],
)
def push__u_r_i_to__account_id(file: UploadFile):
    """
    Push URI to Account
    """
    raise RuntimeError("Should be patched by MCPProxy and never executed")


@app.post(
    '/account/2/verify',
    description=""" This API can be used to verify whether a mobile number or Aadhaar number is already registered with DigiLocker. """,
    tags=['account_validation', 'file_operations'],
    security=[
        UnsuportedSecurityStub(name="None"),
    ],
)
def verify__account_id(file: UploadFile):
    """
    Verify Account
    """
    raise RuntimeError("Should be patched by MCPProxy and never executed")


@app.get(
    '/oauth2/1/authorize',
    description=""" Call to this API starts authorization flow using OAuth 2.0 protocol. This isn't an API call—it's a DigiLocker web page that lets the user sign in to DigiLocker and authorize your application to access user’s data. After the user decides whether or not to authorize your app, they will be redirected to the redirect link provided by your application. """,
    tags=['token_management'],
    security=[
        UnsuportedSecurityStub(name="None"),
    ],
)
def get__authorization__code_id(
    client_id: Optional[str] = None,
    response_type: str = ...,
    redirect_uri: str = ...,
    state: str = ...,
    code_challenge: Optional[CodeChallenge1] = Query(None, alias='Code_challenge'),
    code_challenge_method: Optional[CodeChallengeMethod1] = Query(
        None, alias='Code_challenge_method'
    ),
    dl_flow: Optional[str] = None,
    verified_mobile: Optional[int] = Query(None, alias='Verified_mobile'),
):
    """
    Get Authorization Code
    """
    raise RuntimeError("Should be patched by MCPProxy and never executed")


@app.post(
    '/oauth2/1/code',
    description=""" The client device calls the DigiLocker API to get the device code by providing the client_id issued to the device OEM and either the username or the mobile number of the user. DigiLocker responds with a device code and then sends an OTP on the mobile number and email address associated with the user’s account. The masked mobile number and email address is also sent in response. The device should use these values to notify the users about the mobile and email address on which the OTP has been sent. """,
    tags=['token_management'],
    security=[
        UnsuportedSecurityStub(name="None"),
    ],
)
def get__device__code_id(body: DeviceAuthorizationCode = None):
    """
    Get Device Code
    """
    raise RuntimeError("Should be patched by MCPProxy and never executed")


@app.post(
    '/oauth2/1/file/upload',
    description=""" This API can be used to save/upload a file to uploaded documents in DigiLocker. The allowed file types are JPG, JPEG, PNG and PDF. The file size must not exceed 10MB. """,
    tags=['file_operations'],
    security=[
        HTTPBearer(name="None"),
    ],
)
def upload__file_to__locker_id(
    path: Optional[str] = None, hmac: Optional[str] = None, request: Request = ...
):
    """
    Upload file to locker
    """
    raise RuntimeError("Should be patched by MCPProxy and never executed")


@app.get(
    '/oauth2/1/file/{uri}',
    description=""" Returns a file from URI. This API can be used to fetch both issued document and uploaded document. """,
    tags=['file_operations', 'document_access'],
    security=[
        HTTPBearer(name="None"),
    ],
)
def get__file_from__u_r_i_id(uri: str):
    """
    Get File from URI
    """
    raise RuntimeError("Should be patched by MCPProxy and never executed")


@app.get(
    '/oauth2/1/files/',
    description=""" Returns the list of meta-data about documents or folders in user’s DigiLocker in a specific location. """,
    tags=['file_operations', 'document_access'],
    security=[
        HTTPBearer(name="None"),
    ],
)
def get__list_of__self__uploaded__documents():
    """
    Get List of Self Uploaded Documents
    """
    raise RuntimeError("Should be patched by MCPProxy and never executed")


@app.get(
    '/oauth2/1/files/issued',
    description=""" Returns the list of meta-data about issued documents in user’s DigiLocker. """,
    tags=['file_operations', 'document_access'],
    security=[
        HTTPBearer(name="None"),
    ],
)
def get__list_of_issued__documents__version1_id():
    """
    Issued Documents
    """
    raise RuntimeError("Should be patched by MCPProxy and never executed")


@app.get(
    '/oauth2/1/files/{id}',
    description=""" Returns the list of meta-data about documents or folders in user’s DigiLocker in a specific location. """,
    tags=['file_operations', 'document_access', 'user_information_retrieval'],
    security=[
        HTTPBearer(name="None"),
    ],
)
def get__list_of__self__uploaded__documents_id(id: str):
    """
    Get List of Self Uploaded Documents
    """
    raise RuntimeError("Should be patched by MCPProxy and never executed")


@app.post(
    '/oauth2/1/pull/doctype',
    description=""" Returns a list of documents/certificates issued by an issuer organization registered with DigiLocker. """,
    tags=['document_access', 'issuer_data_management'],
    security=[
        UnsuportedSecurityStub(name="None"),
    ],
)
def get__list_of__documents__provided_by_an__issuer_id(request: Request):
    """
    Get List of Documents Provided by an Issuer
    """
    raise RuntimeError("Should be patched by MCPProxy and never executed")


@app.post(
    '/oauth2/1/pull/issuers',
    description=""" Returns the list of issuers registered with DigiLocker. """,
    tags=['issuer_data_management', 'user_information_retrieval', 'document_access'],
    security=[
        UnsuportedSecurityStub(name="None"),
    ],
)
def get__list_of__issuers_id(request: Request):
    """
    Get List of Issuers
    """
    raise RuntimeError("Should be patched by MCPProxy and never executed")


@app.post(
    '/oauth2/1/pull/parameters',
    description=""" Returns a list of parameters required to search a document/certificate of an issuer organization registered with DigiLocker. These parameters are used to pull a document from issuer’s repository using Pull Document API mentioned in subsequent section. """,
    tags=['document_access', 'user_information_retrieval'],
    security=[
        UnsuportedSecurityStub(name="None"),
    ],
)
def get__search__parameters_for_a__document_id(request: Request):
    """
    Get Search Parameters for a Document
    """
    raise RuntimeError("Should be patched by MCPProxy and never executed")


@app.post(
    '/oauth2/1/pull/pulldocument',
    description=""" This API allows a client application to search a document/certificate from issuer’s repository using the parameters provided by a user. The searched document is saved in user’s issued document section of DigiLocker if the search is successful. """,
    tags=['file_operations', 'document_access', 'user_information_retrieval'],
    security=[
        HTTPBearer(name="None"),
    ],
)
def pull__document_id(request: Request):
    """
    Pull Document
    """
    raise RuntimeError("Should be patched by MCPProxy and never executed")


@app.post(
    '/oauth2/1/revoke',
    description=""" Client applications can revoke a previously obtained refresh or access token when it is no longer needed. This is done by making a request to the token revocation endpoint. DigiLocker will invalidate the specified token and, if applicable, other tokens based on the same authorisation grant. This API may be used to sign out a user from DigiLocker. This API will work for server based web applications, mobile application and limited input devices. """,
    tags=['token_management'],
    security=[
        UnsuportedSecurityStub(name="None"),
    ],
)
def get_token_revocation_id(body: Oauth21RevokePostRequest = None):
    """
    Revoke Token.
    """
    raise RuntimeError("Should be patched by MCPProxy and never executed")


@app.post(
    '/oauth2/1/token',
    description=""" This endpoint only applies to apps using the authorization code flow. An app calls this endpoint to acquire a bearer token once the user has authorized the app. Calls to /oauth2/1/token need to be authenticated using the app's key and secret. These can either be passed as application/x-www-form-urlencoded POST parameters (see parameters below) or via HTTP basic authentication. If basic authentication is used, the app key should be provided as the username, and the app secret should be provided as the password. """,
    tags=['token_management'],
)
def getaccesstoken_id(body: Oauth21TokenPostRequest):
    """
    Get Access Token
    """
    raise RuntimeError("Should be patched by MCPProxy and never executed")


@app.get(
    '/oauth2/1/user',
    description=""" Client applications can call this API to get the DigiLocker Id, name, date of birth and gender of the account holder. An access token is required to call this API. The API will return the user details of the account with which the access token is linked. It is strongly recommended that the API can be called by client application only once after acquiring the access token. Since the user details do not change, the client application may store the values and use them when necessary than calling this API repeatedly. """,
    tags=['user_information_retrieval'],
    security=[
        HTTPBearer(name="None"),
    ],
)
def account__detail__a_p_i_id():
    """
    Get User Details
    """
    raise RuntimeError("Should be patched by MCPProxy and never executed")


@app.get(
    '/oauth2/1/xml/{uri}',
    description=""" Returns the certificate data in machine readable XML format for a URI. This API can be used to only for issued documents. The XML data may not be available for all documents. If the XML data is available for a particular document, the mime parameter in Get List of Issued Documents API will contain application/xml. Please refer to Digital Locker XML Certificate Formats for more details of XML formats of various documents. """,
    tags=['document_access', 'data_collection_and_statistics'],
    security=[
        HTTPBearer(name="None"),
    ],
)
def get__certificate__data_in__x_m_l__format_from__u_r_i_id(uri: str):
    """
    Get Certificate Data in XML Format from URI
    """
    raise RuntimeError("Should be patched by MCPProxy and never executed")


@app.get(
    '/oauth2/2/files/issued',
    description=""" Returns the list of meta-data about issued documents in user’s DigiLocker. """,
    tags=['file_operations', 'document_access', 'issuer_data_management'],
)
def get__list_of_issued__documents_id():
    """
    Issued Documents
    """
    raise RuntimeError("Should be patched by MCPProxy and never executed")


@app.get(
    '/oauth2/2/xml/eaadhaar',
    description=""" Returns e-Aadhaar data in XML format for the account. """,
    tags=[
        'user_information_retrieval',
        'document_access',
        'data_collection_and_statistics',
    ],
    security=[
        HTTPBearer(name="None"),
    ],
)
def get_e__aadhaar__data_in__x_m_l__format_id():
    """
    Get e-Aadhaar Data in XML Format
    """
    raise RuntimeError("Should be patched by MCPProxy and never executed")


@app.post(
    '/signup/1/demoauthverify',
    description=""" This API is used to verify the OTP sent by DigiLocker during the sign up API call above. """,
    tags=['account_validation'],
    security=[
        UnsuportedSecurityStub(name="None"),
    ],
)
def verify__o_t_p_id(file: UploadFile):
    """
    Verify OTP
    """
    raise RuntimeError("Should be patched by MCPProxy and never executed")


@app.post(
    '/signup/2/demoauth',
    description=""" This API is used to validate Aadhaar details and verify the mobile number by generating an OTP. This API call, if successful, will be followed by verify OTP call by the partner application if the user is online or available to perform OTP validation as indicated in verification parameter """,
    tags=['file_operations', 'account_validation'],
    security=[
        UnsuportedSecurityStub(name="None"),
    ],
)
def s_i_g_n__u_p_id(file: UploadFile):
    """
    SIGN UP
    """
    raise RuntimeError("Should be patched by MCPProxy and never executed")


@app.post(
    '/statistics/1/counts',
    description=""" Returns DigiLocker statistics such as the count of users, authentic documents, issuers and requesters as on a specific date. """,
    tags=['data_collection_and_statistics'],
    security=[
        UnsuportedSecurityStub(name="None"),
    ],
)
def get__statistics_id(file: UploadFile):
    """
    Get Statistics
    """
    raise RuntimeError("Should be patched by MCPProxy and never executed")


if __name__ == "__main__":
    parser = argparse.ArgumentParser(description="MCP Server")
    parser.add_argument(
        "transport",
        choices=["stdio", "sse", "streamable-http"],
        help="Transport mode (stdio, sse or streamable-http)",
    )
    args = parser.parse_args()

    if "CONFIG_PATH" in os.environ:
        config_path = os.environ["CONFIG_PATH"]
        app.load_configuration(config_path)

    if "CONFIG" in os.environ:
        config = os.environ["CONFIG"]
        app.load_configuration_from_string(config)

    if "SECURITY" in os.environ:
        security_params = BaseSecurity.parse_security_parameters_from_env(
            os.environ,
        )

        app.set_security_params(security_params)

    mcp_settings = json.loads(os.environ.get("MCP_SETTINGS", "{}"))

    app.get_mcp(**mcp_settings).run(transport=args.transport)
