# generated by fastapi-codegen:
#   filename:  openapi.yaml
#   timestamp: 2025-06-28T18:31:14+00:00

from __future__ import annotations

from enum import Enum
from typing import Any, Dict, List, Optional, Union

from pydantic import BaseModel, Field, RootModel, constr


class Eaadhar(Enum):
    Y = 'Y'
    N = 'N'


class Gender(Enum):
    M = 'M'
    F = 'F'
    T = 'T'


class AccessResponse(BaseModel):
    access_token: str = Field(
        ...,
        description='The access token that can be used to call the DigiLocker APIs.',
        examples=['bc125c212a4b03a9a188a858be5a163f379e878a'],
    )
    digilocker_id: str = Field(
        ...,
        description='A unique 36 character DigiLocker Id of the user account.',
        examples=['123e4567-e89b-12d3-a456-426655440000'],
    )
    dob: int = Field(
        ...,
        description='This is date of birth of the user as registered with DigiLocker in DDMMYYYY format.',
        examples=['31121970'],
    )
    eaadhar: Eaadhar = Field(
        ...,
        description='This indicates whether eAadhaar data is available for this account. Possible values are Y and N.',
    )
    expires_in: int = Field(
        ...,
        description='The duration in seconds for which the access token is valid',
        examples=[3600],
    )
    gender: Gender = Field(
        ...,
        description='This is gender of the user as registered with DigiLocker. The possible values are M, F, T for male, female and transgender respectively.',
    )
    name: str = Field(
        ...,
        description='The name of the user as registered with DigiLocker.',
        examples=['Sunil Kumar'],
    )
    reference_key: str = Field(
        ...,
        description='A unique reference of the user account.',
        examples=['1c66bec26364cd6fefaabc6cae91840a'],
    )
    refresh_token: str = Field(
        ...,
        description='The refresh token used to refresh the above access token when it expires. Please refer to Refresh Access Token API for more details.',
        examples=['a47ab18c593703e4f83a274694db7422a8cfcb8f'],
    )
    scope: str = Field(..., description='Scope of the token.')
    token_type: str = Field(
        ...,
        description='The type of token which will always be Bearer.',
        examples=['Bearer'],
    )


class GrantType(Enum):
    authorization_code = 'authorization_code'


class AccessToken(BaseModel):
    client_id: str = Field(..., examples=['ABCDEFG'])
    client_secret: str = Field(..., examples=['a123456abcdeghijk7890'])
    code: Optional[str] = Field(
        None, examples=['ca82123a5476aa2f5e4638957c0ecc55c6ec07c1']
    )
    code_verifier: Optional[str] = Field(None, examples=['a123456abca'])
    grant_type: GrantType
    redirect_uri: Optional[str] = Field(
        None, examples=['https://ndh.digitallocker.gov.in/oauth2-redirect.html']
    )


class AuthTokenResponse(BaseModel):
    access_token: str = Field(
        ...,
        description='The access token that can be used to call the\n    DigiLocker APIs.',
        examples=['bc125c212a4b03a9a188a858be5a163f379e878a'],
    )
    expires_in: int = Field(
        ...,
        description='The duration in seconds for which the access token is\n            valid.',
        examples=[3600],
    )
    refresh_token: str = Field(
        ...,
        description='The refresh token used to refresh the above access\n  token when it expires. This will value will be\n  returned only in case of web applications and not be\n  returned for limited input devices.',
        examples=['ad6f4004cc3e53f56bda391fe485fc4d32928061'],
    )
    scope: str = Field(..., description='Scope of the token.')
    token_type: str = Field(
        ...,
        description='The type of token which will always be Bearer.',
        examples=['Bearer'],
    )


class DemoAuth(BaseModel):
    clientid: Optional[str] = Field(
        None,
        description='Provide the client id that was created during the application registration process on Partners Portal.',
    )
    consent: Optional[str] = Field(
        None,
        description='The consent indicator from the user for performing demographic authentication using Aadhaar details. This Partner Application must capture the user consent for performing the Aadhaar demographic authentication. The possible values are ‘Y’ and ‘N’. The sign up request will be processed only when this indicator is ‘Y’.',
    )
    demoauth: Optional[str] = Field(
        None,
        description='The parameter indicates whether Aadhaar demographic authentication must be successful for creating DigiLocker account. The possible values are ‘Y’ and ‘N’. The value of ‘Y’ will perform Aadhaar demographic authentication and will return errors if any in response. The value of ‘N’ will also perform Aadhaar demographic authentication but will return any error in case of authentication failure. It will create a basic mobile based account for the user. Value ‘N’ should be used when the user account needs to be created in the absence of the user.',
    )
    dob: Optional[int] = Field(
        None,
        description='This is date of birth of the user as mentioned in Aadhaar in DDMMYYYY format.',
    )
    gender: Optional[Gender] = Field(
        None,
        description='This is gender of the user as mentioned in Aadhaar. The possible values are M, F, T for male, female and transgender respectively.',
    )
    hmac: Optional[bytes] = Field(
        None,
        description='Provide SHA-256 encrypted value of the client secret, clientid and ts parameters above concatenated in this sequence (client secret, clientid, ts). The hmac parameter is used by DigiLocker to ensure the data integrity and authentication of the request. Use the Client Secret Key generated during the application registration process on Partners Portal as the client secret.',
    )
    mobile: Optional[int] = Field(
        None,
        description='This is the mobile number of the user. DigiLocker will check whether an account exists for this mobile number. Either uid or mobile is required to verify whether an account exists.',
    )
    name: Optional[str] = Field(
        None, description='This is name of the user as mentioned in Aadhaar.'
    )
    ts: Optional[str] = Field(
        None,
        description='Provide a timestamp value in UNIX (or POSIX) format in IST time zone in seconds. This timestamp value must not be older than 30 minutes.',
    )
    uid: Optional[int] = Field(
        None,
        description='This is the Aadhaar number of the user. DigiLocker will check whether an account exists for this Aadhaar number. Either uid or mobile is required to verify whether an account exists.',
    )
    verification: Optional[str] = Field(
        None,
        description='The parameter indicates whether the mobile number provided above should be validated by DigiLocker. If this parameter is ‘Y’, the DigiLocker sends an OTP to verify the mobile number. In this case the client application will call the second API to validate the OTP. The user will be signed on only after successful OTP validation. This flow should be used when the user account is created by user himself/herself or the user is present to provide the OTP. If this parameter is ‘N’, the user account will be created without OTP validation. The OTP validation will be performed when the user signs in for the first time in DigiLocker. This flow should be used when the user account needs to be created in the absence of the user.',
    )


class Details(BaseModel):
    access_token: str = Field(
        ...,
        description='The access token that can be used to call the DigiLocker APIs.',
        examples=['bc125c212a4b03a9a188a858be5a163f379e878a'],
    )
    expires_in: str = Field(
        ...,
        description='The duration in seconds for which the access token is valid.',
        examples=[3600],
    )
    mobile: int = Field(
        ...,
        description='The masked mobile number of the user on which the OTP has been sent.           ',
        examples=['******3712'],
    )
    refresh_token: str = Field(
        ...,
        description='The refresh token used to refresh the above access token when it expires. Please refer to Refresh Access Token API for more details.',
        examples=['a47ab18c593703e4f83a274694db7422a8cfcb8f'],
    )
    scope: str = Field(..., description='Scope of the token', examples=[''])
    token_type: str = Field(
        ...,
        description='The type of token which will always be Bearer.',
        examples=['Bearer'],
    )


class DemoAuthResponse(BaseModel):
    details: Optional[Details] = None


class DemoAuthVerify(BaseModel):
    clientid: Optional[str] = Field(
        None,
        description='Provide the client id that was created during the application registration process on Partners Portal.',
    )
    hmac: Optional[bytes] = Field(
        None,
        description='Provide SHA-256 encrypted value of the client secret, clientid and ts parameters above concatenated in this sequence (client secret, clientid, ts). The hmac parameter is used by DigiLocker to ensure the data integrity and authentication of the request. Use the Client Secret Key generated during the application registration process on Partners Portal as the client secret.',
    )
    mobile: Optional[int] = Field(
        None,
        description='This is the mobile number of the user. DigiLocker will check whether an account exists for this mobile number. Either uid or mobile is required to verify whether an account exists.',
    )
    otp: Optional[int] = Field(None, description='The OTP provided by the user.')
    ts: Optional[str] = Field(
        None,
        description='Provide a timestamp value in UNIX (or POSIX) format in IST time zone in seconds. This timestamp value must not be older than 30 minutes.',
    )


class Details1(BaseModel):
    access_token: str = Field(
        ...,
        description='The access token that can be used to call the DigiLocker APIs.',
        examples=['bc125c212a4b03a9a188a858be5a163f379e878a'],
    )
    expires_in: str = Field(
        ...,
        description='The duration in seconds for which the access token is valid.',
        examples=[3600],
    )
    refresh_token: str = Field(
        ...,
        description='The refresh token used to refresh the above access token when it expires. Please refer to Refresh Access Token API for more details.',
        examples=['a47ab18c593703e4f83a274694db7422a8cfcb8f'],
    )
    scope: str = Field(..., description='Scope of the token', examples=[''])
    token_type: str = Field(
        ...,
        description='The type of token which will always be Bearer.',
        examples=['Bearer'],
    )


class DemoAuthVerifyResponse(BaseModel):
    details: Optional[Details1] = None


class DeviceAccessToken(BaseModel):
    client_id: Optional[str] = Field(
        None,
        description='Provide the client id that was created during the application registration process on Partners Portal.',
    )
    device_code: Optional[str] = Field(
        None,
        description='The device verification code. The device_code field from Get Device Code Response.',
    )
    dl_otp: Optional[str] = Field(None, description='The OTP collected from the user')
    grant_type: Optional[str] = Field(
        None,
        description='The grant type, which must be “urn:ietf:params:oauth:grant-type:device_code”.',
        examples=['urn:ietf:params:oauth:grant-type:device_code'],
    )


class DeviceAuthorizationCode(BaseModel):
    client_id: Optional[str] = None
    dl_mobile: Optional[int] = Field(
        None,
        description='Mobile number associated with DigiLocker account of the\n  user. The client device accepts the mobile number on the device from user and sends it in this parameter. Either the username or the mobile number must be provided.',
    )
    dl_username: Optional[str] = Field(
        None,
        description='DigiLocker username of the user. The client device accepts the username on the device from user and sends the username in this parameter. Either the username or the mobile number must be provided.   ',
    )
    response_type: Optional[str] = Field(
        None,
        description='The parameter must be set to device_code.',
        examples=['device_code'],
    )


class DeviceAuthorizationCodeResponse(BaseModel):
    device_code: str = Field(
        ..., description='The device verification code.', examples=['74tq5miHKB']
    )
    dl_masked_email: str = Field(
        ...,
        description='The masked email on which the OTP is sent.',
        examples=['xxxxxx@gmail.com'],
    )
    dl_masked_mobile: int = Field(
        ...,
        description='The masked mobile number on which the OTP is sent.',
        examples=['XXXXXX1234'],
    )
    expires_in: int = Field(
        ...,
        description='The duration in seconds for which the code is valid.',
        examples=[600],
    )


class DocType(BaseModel):
    clientid: Optional[str] = Field(
        None,
        description='Provide the client id that was created during the application registration process on Partners Portal.',
    )
    hmac: Optional[bytes] = Field(
        None,
        description='Provide SHA-256 encrypted value of the client secret, clientid and ts parameters above concatenated in this sequence (client secret, clientid, ts). The hmac parameter is used by DigiLocker to ensure the data integrity and authentication of the request. Use the Client Secret Key generated during the application registration process on Partners Portal as the client secret.',
    )
    orgid: Optional[str] = Field(
        None,
        description='The organization id for the issuer in DigiLocker. This organization id is returned in Get List of Issuers API mentioned earlier.',
    )
    ts: Optional[str] = Field(
        None,
        description='Provide a timestamp value in UNIX (or POSIX) format in IST time zone in seconds. This timestamp value must not be older than 30 minutes.',
    )


class Document(BaseModel):
    description: constr(min_length=1)
    doctype: constr(min_length=1)


class DocTypeResponse(BaseModel):
    documents: List[Document] = Field(..., min_length=1)


class X509Data(BaseModel):
    X509Certificate: constr(min_length=1)
    X509SubjectName: constr(min_length=1)


class KeyInfo(BaseModel):
    X509Data_1: X509Data = Field(..., alias='X509Data')


class CanonicalizationMethod(BaseModel):
    Algorithm: constr(min_length=1)


class DigestMethod(BaseModel):
    Algorithm: constr(min_length=1)


class Transform(BaseModel):
    Algorithm: constr(min_length=1)


class Transforms(BaseModel):
    Transform_1: Transform = Field(..., alias='Transform')


class Reference(BaseModel):
    DigestMethod_1: DigestMethod = Field(..., alias='DigestMethod')
    DigestValue: constr(min_length=1)
    Transforms_1: Transforms = Field(..., alias='Transforms')
    URI: str


class SignatureMethod(BaseModel):
    Algorithm: constr(min_length=1)


class SignedInfo(BaseModel):
    CanonicalizationMethod_1: CanonicalizationMethod = Field(
        ..., alias='CanonicalizationMethod'
    )
    Reference_1: Reference = Field(..., alias='Reference')
    SignatureMethod_1: SignatureMethod = Field(..., alias='SignatureMethod')


class Signature(BaseModel):
    KeyInfo_1: KeyInfo = Field(..., alias='KeyInfo')
    SignatureValue: constr(min_length=1)
    SignedInfo_1: SignedInfo = Field(..., alias='SignedInfo')
    xmlns: constr(min_length=1)


class LData(BaseModel):
    co: constr(min_length=1)
    country: constr(min_length=1)
    dist: constr(min_length=1)
    lang: constr(min_length=1)
    lm: constr(min_length=1)
    loc: constr(min_length=1)
    name: constr(min_length=1)
    pc: constr(min_length=1)
    state: constr(min_length=1)
    vtc: constr(min_length=1)


class Poa(BaseModel):
    co: constr(min_length=1)
    country: constr(min_length=1)
    dist: constr(min_length=1)
    lm: constr(min_length=1)
    loc: constr(min_length=1)
    pc: constr(min_length=1)
    state: constr(min_length=1)
    vtc: constr(min_length=1)


class Poi(BaseModel):
    dob: constr(min_length=1)
    gender: constr(min_length=1)
    name: constr(min_length=1)


class Prn(BaseModel):
    text: constr(min_length=1)
    type: constr(min_length=1)


class UidData(BaseModel):
    LData_1: LData = Field(..., alias='LData')
    Pht: constr(min_length=1)
    Poa_1: Poa = Field(..., alias='Poa')
    Poi_1: Poi = Field(..., alias='Poi')
    Prn_1: Prn = Field(..., alias='Prn')
    tkn: constr(min_length=1)
    uid: constr(min_length=1)


class KycRes(BaseModel):
    Rar: constr(min_length=1)
    Signature_1: Signature = Field(..., alias='Signature')
    UidData_1: UidData = Field(..., alias='UidData')
    code: constr(min_length=1)
    ret: constr(min_length=1)
    ts: constr(min_length=1)
    ttl: constr(min_length=1)
    txn: constr(min_length=1)


class EaadharXamlSchema(BaseModel):
    KycRes_1: KycRes = Field(..., alias='KycRes')


class FileUpload(BaseModel):
    Content_Type: Optional[str] = Field(
        None,
        alias='Content-Type',
        description='The mime type of the file e.g. image/jpg, image/jpeg, image/png, application/pdf.',
    )


class Details2(BaseModel):
    Path: str = Field(
        ...,
        description='The destination path of the file in DigiLocker including filename.',
    )
    size: str = Field(..., description='Size of file.')


class FileUploadResponse(BaseModel):
    details: Optional[Details2] = None


class GetStatistics(BaseModel):
    clientid: Optional[str] = Field(
        None,
        description='Provide the client id that was created during the application registration process on Partners Portal.',
    )
    hmac: Optional[bytes] = Field(
        None,
        description='Provide SHA-256 encrypted value of the client secret, clientid and ts parameters above concatenated in this sequence (client secret, clientid, ts). The hmac parameter is used by DigiLocker to ensure the data integrity and authentication of the request. Use the Client Secret Key generated during the application registration process on Partners Portal as the client secret.',
    )
    ts: Optional[str] = Field(
        None,
        description='Provide a timestamp value in UNIX (or POSIX) format in IST time zone in seconds. This timestamp value must not be older than 30 minutes.',
    )


class Details21(BaseModel):
    count: Optional[int] = Field(
        None,
        description='Count of cumulative user registrations in the given month.',
        examples=['124794'],
    )
    id: Optional[int] = Field(
        None, description='Unique id of the list item.', examples=['18496']
    )
    month: Optional[int] = Field(
        None,
        description='Month of the year in numeric format with January as 1',
        examples=['5'],
    )
    year: Optional[int] = Field(
        None, description='Year in YYYY format', examples=['2018']
    )


class MonthwiseRegistations(BaseModel):
    count: Optional[int] = Field(
        None,
        description='Count of cumulative user registrations in the given month.',
        examples=['124794'],
    )
    details2: Optional[Details21] = None
    id: Optional[int] = Field(
        None, description='Unique id of the list item.', examples=['18496']
    )
    month: Optional[int] = Field(
        None,
        description='Month of the year in numeric format with January as 1',
        examples=['5'],
    )
    year: Optional[int] = Field(
        None, description='Year in YYYY format', examples=['2018']
    )


class Details3(BaseModel):
    count: Optional[int] = Field(
        None,
        description='Count of cumulative user authentic documents in the given year.',
        examples=['1000548093'],
    )
    id: Optional[int] = Field(
        None, description='Unique id of the list item.', examples=['18350']
    )
    year: Optional[int] = Field(
        None, description='Year in YYYY format.', examples=['2017']
    )


class Details11(BaseModel):
    count: Optional[int] = Field(
        None,
        description='Count of cumulative user authentic documents in the given year.',
        examples=['2410543684'],
    )
    id: Optional[int] = Field(
        None, description='Unique id of the list item.', examples=['18354']
    )
    year: Optional[int] = Field(
        None, description='Year in YYYY format.', examples=['2018']
    )


class Details22(BaseModel):
    count: Optional[int] = Field(
        None,
        description='Count of cumulative user authentic documents in the given year.  ',
        examples=['3520475277'],
    )
    id: Optional[int] = Field(
        None, description='Unique id of the list item.', examples=['18567']
    )
    year: Optional[int] = Field(
        None, description='Year in YYYY format.', examples=['2019']
    )


class YearwiseAuthenticDocuments(BaseModel):
    count: Optional[int] = Field(
        None,
        description='Count of cumulative user authentic documents in\n  the given year.',
        examples=['10134567'],
    )
    details: Optional[Details3] = None
    details1: Optional[Details11] = None
    details2: Optional[Details22] = None
    id: Optional[int] = Field(
        None, description='Unique id of the list item.', examples=['18347']
    )
    year: Optional[int] = Field(
        None, description='Year in YYYY format.', examples=['2016']
    )


class GetStatisticsResponse(BaseModel):
    authentic_documents: str = Field(
        ...,
        description='Count of authentic documents available through DigiLocker.',
        examples=['3520475277'],
    )
    count_as_on: str = Field(
        ...,
        description='The date on which this statistics is generated.',
        examples=['31072019'],
    )
    issuers: str = Field(
        ...,
        description='Count of issuer organizations registered on DigiLocker.',
        examples=['134'],
    )
    monthwise_registations: MonthwiseRegistations = Field(
        ..., description='List of last 12 months cumulative user registrations'
    )
    requestors: str = Field(
        ...,
        description='Count of requester organizations registered on DigiLocker.',
        examples=['45'],
    )
    users: str = Field(
        ...,
        description='Count of registered users on DigiLocker.',
        examples=['25873490'],
    )
    yearwise_authentic_documents: YearwiseAuthenticDocuments = Field(
        ...,
        description='List of cumulative year-wise counts of authentic documents in DigiLocker.',
    )


class Issuer(BaseModel):
    clientid: Optional[str] = Field(
        None,
        description='Provide the client id that was created during the application registration process on Partners Portal.',
    )
    hmac: Optional[bytes] = Field(
        None,
        description='Provide SHA-256 encrypted value of the client secret, clientid and ts parameters above concatenated in this sequence (client secret, clientid, ts). The hmac parameter is used by DigiLocker to ensure the data integrity and authentication of the request. Use the Client Secret Key generated during the application registration process on Partners Portal as the client secret.',
    )
    ts: Optional[str] = Field(
        None,
        description='Provide a timestamp value in UNIX (or POSIX) format in IST time zone in seconds. This timestamp value must not be older than 30 minutes.',
    )


class Issuer1(BaseModel):
    categories: constr(min_length=1)
    description: str
    issuerid: constr(min_length=1)
    name: constr(min_length=1)
    orgid: constr(min_length=1)


class IssuerResponse(BaseModel):
    issuers: List[Issuer1] = Field(..., min_length=1)


class PullDocumentSchema(BaseModel):
    chasis_no: Optional[str] = Field(
        None,
        description='Other parameters required for fetching a document as listed in paramname field of Get Search Parameters API.',
    )
    consent: Optional[str] = Field(
        None,
        description='The consent indicator from the user for performing demographic authentication using Aadhaar details. This Partner Application must capture the user consent for performing the Aadhaar demographic authentication. The possible values are ‘Y’ and ‘N’. The sign up request will be processed only when this indicator is ‘Y’.',
    )
    doctype: Optional[str] = Field(
        None, description='A 5 character unique document type provided by DigiLocker.'
    )
    orgid: Optional[str] = Field(
        None,
        description='The organization id for the issuer in DigiLocker. This organization id is returned in Get List of Issuers API mentioned above.',
    )
    reg_no: Optional[str] = Field(
        None,
        description='Other parameters required for fetching a document as listed in paramname field of Get Search Parameters API.',
    )


class PushUri(BaseModel):
    action: Optional[str] = Field(
        None,
        description='Action that needs to be taken for the Aadhaar number and URI combination. Possible values are A for adding a new URI, U for updating an already added URI details or D for deleting the URI.',
    )
    clientid: Optional[str] = Field(
        None,
        description='Provide the client id that was created during the application registration process on Partners Portal.',
    )
    digilockerid: Optional[int] = Field(
        None,
        description='This is the DigiLocker Id of the user that was acquired using Get User Details API.',
    )
    docid: Optional[str] = Field(
        None,
        description='A unique number of the document. This id will be unique within the document type issued by the issuer.',
    )
    hmac: Optional[bytes] = Field(
        None,
        description='Provide SHA-256 encrypted value of the client secret, clientid and ts parameters above concatenated in this sequence (client secret, clientid, ts). The hmac parameter is used by DigiLocker to ensure the data integrity and authentication of the request. Use the Client Secret Key generated during the application registration process on Partners Portal as the client secret.',
    )
    issuedate: Optional[str] = Field(
        None, description='The issue date of the document in DDMMYYYY format.'
    )
    ts: Optional[str] = Field(
        None,
        description='Provide a timestamp value in UNIX (or POSIX) format in IST time zone in seconds. This timestamp value must not be older than 30 minutes.',
    )
    uri: Optional[str] = Field(
        None, description='This is the unique identifier of the document.'
    )
    validfrom: Optional[int] = Field(
        None,
        description='The date from which the document is valid in DDMMYYYY format. This may be same as the issue date.',
    )
    validto: Optional[str] = Field(
        None, description='The expiry date of the document in DDMMYYYY format.'
    )


class RefreshAccessToken(BaseModel):
    grant_type: str = Field(..., examples=['refresh_token'])
    refresh_Token: str = Field(
        ..., examples=['a47ab18c593703e4f83a274694db7422a8cfcb8f']
    )


class GrantType1(Enum):
    refresh_token = 'refresh_token'


class RefreshToken(BaseModel):
    client_id: str = Field(..., examples=['ABCDEFG'])
    client_secret: str = Field(..., examples=['a123456abcdeghijk7890'])
    grant_type: GrantType1
    refresh_token: str = Field(
        ..., examples=['ca82123a5476aa2f5e4638957c0ecc55c6ec07c1']
    )


class Response1(BaseModel):
    error: Optional[str] = Field(None, description='repository_service_inactive')
    error_description: Optional[str] = Field(None, description='Internal server error')


class Response10(BaseModel):
    error: Optional[str] = Field(None, description='mobile_exists')
    error_description: Optional[str] = Field(
        None, description='A DigiLocker account already exists with this mobile number.'
    )


class Response11(BaseModel):
    error: Optional[str] = Field(None, description='auth_failure')
    error_description: Optional[str] = Field(
        None,
        description='The data on Aadhaar does not match with one or more of Aadhaar, Name, DOB and Gender data provided. Aadhaar demographic authentication failure.',
    )


class Response12(BaseModel):
    error: Optional[str] = Field(None, description='invalid_parameter')
    error_description: Optional[str] = Field(
        None,
        description='One or more of the mandatory parameters is missing or invalid. The error description text will contain one or more of the following error texts:|- \uf0b7 uid parameter is missing or invalid \uf0b7 Name parameter is missing or invalid \uf0b7 Dob parameter is missing or invalid \uf0b7 Gender parameter is missing or invalid \uf0b7 Mobile parameter is missing or invalid \uf0b7 Verification parameter is missing or invalid \uf0b7 Consent parameter is missing or invalid \uf0b7 Timestamp parameter is missing or invalid \uf0b7 HMAC parameter is missing or invalid',
    )


class Response13(BaseModel):
    error: Optional[str] = Field(None, description='repository_service_configerror')
    error_description: Optional[str] = Field(
        None,
        description='The issuer service is not available. Please contact DigiLocker support.',
    )


class Response14(BaseModel):
    error: Optional[str] = Field(None, description='invalid_orgid')
    error_description: Optional[str] = Field(
        None, description='The orgid parameter is missing or invalid.'
    )


class Response15(BaseModel):
    error: Optional[str] = Field(None, description='invalid_doctype')
    error_description: Optional[str] = Field(
        None, description='The doctype parameter is missing or invalid.'
    )


class Response16(BaseModel):
    error: Optional[str] = Field(None, description='pull_response_pending')
    error_description: Optional[str] = Field(
        None,
        description='The details provided above do not exactly match with the details on the certificate. Your request has been forwarded to the Issuer department. The Issuer department will verify the details provided above. If the verification is successful, your certificate will be made available in the Issued Documents section of your DigiLocker.',
    )


class Response17(BaseModel):
    error: Optional[str] = Field(None, description='uri_exists')
    error_description: Optional[str] = Field(
        None, description='This document already exists in your Issued Documents.'
    )


class Response18(BaseModel):
    error: Optional[str] = Field(None, description='aadhaar_not_linked')
    error_description: Optional[str] = Field(
        None,
        description='To access issued documents, please link your Aadhaar number to your DigiLocker account.',
    )


class Response2(BaseModel):
    error: Optional[str] = Field(None, description='repository_service_unpublished')
    error_description: Optional[str] = Field(None, description='Internal server error')


class Response3(BaseModel):
    error: Optional[str] = Field(None, description='repository_service_unresponsive')
    error_description: Optional[str] = Field(None, description='Internal server error')


class Response4(BaseModel):
    error: Optional[str] = Field(None, description='repository_service_configerror')
    error_description: Optional[str] = Field(None, description='Internal server error')


class Response5(BaseModel):
    error: Optional[str] = Field(None, description='repository_service_resperror')
    error_description: Optional[str] = Field(None, description='Internal server error')


class Response6(BaseModel):
    error: Optional[str] = Field(None, description='repository_service_exception')
    error_description: Optional[str] = Field(None, description='Internal server error')


class Response7(BaseModel):
    error: Optional[str] = Field(None, description='parameter_missing')
    error_description: Optional[str] = Field(
        None, description='One or more of the mandatory parameters is missing'
    )


class Response8(BaseModel):
    error: Optional[str] = Field(None, description='invalid_ts')
    error_description: Optional[str] = Field(
        None, description='Timestamp parameter is invalid'
    )


class Response9(BaseModel):
    error: Optional[str] = Field(None, description='hmac_mismatch')
    error_description: Optional[str] = Field(None, description='HMAC does not match')


class ResponseFive(BaseModel):
    error: Optional[str] = Field(None, description='otp_error')
    error_description: Optional[str] = Field(
        None,
        description='OTP could not be sent as the account may not have a valid mobile or a valid email.',
    )


class ResponseFour(BaseModel):
    error: Optional[str] = Field(None, description='multiple_mobile_accounts')
    error_description: Optional[str] = Field(
        None,
        description='The mobile number provided is associated with more than one DigiLocker accounts. Please login using username.',
    )


class ResponseOne(BaseModel):
    error: Optional[str] = Field(None, description='invalid_response_type')
    error_description: Optional[str] = Field(
        None, description='The response_type parameter is invalid'
    )


class ResponseSeven(BaseModel):
    error: Optional[str] = Field(None, description='partner_service_unresponsive')
    error_description: Optional[str] = Field(None, description='Internal server error')


class ResponseSix(BaseModel):
    error: Optional[str] = Field(None, description='unexpected_error')
    error_description: Optional[str] = Field(None, description='Internal server error')


class ResponseThree(BaseModel):
    error: Optional[str] = Field(None, description='invalid_mobile')
    error_description: Optional[str] = Field(
        None, description='The dl_mobile parameter is invalid'
    )


class ResponseTwo(BaseModel):
    error: Optional[str] = Field(None, description='invalid_username')
    error_description: Optional[str] = Field(
        None, description='The dl_username parameter is invalid'
    )


class SearchParameters(BaseModel):
    clientid: Optional[str] = Field(
        None,
        description='Provide the client id that was created during the application registration process on Partners Portal.',
    )
    doctype: Optional[str] = Field(
        None, description='A 5 character unique document type provided by DigiLocker.'
    )
    hmac: Optional[bytes] = Field(
        None,
        description='Provide SHA-256 encrypted value of the client secret, clientid and ts parameters above concatenated in this sequence (client secret, clientid, ts). The hmac parameter is used by DigiLocker to ensure the data integrity and authentication of the request. Use the Client Secret Key generated during the application registration process on Partners Portal as the client secret.',
    )
    orgid: Optional[str] = Field(
        None,
        description='The organization id for the issuer in DigiLocker. This organization id is returned in Get List of Issuers API mentioned earlier.',
    )
    ts: Optional[str] = Field(
        None,
        description='Provide a timestamp value in UNIX (or POSIX) format in IST time zone in seconds. This timestamp value must not be older than 30 minutes.',
    )


class SearchParametersResponseItem(BaseModel):
    example: constr(min_length=1)
    label: constr(min_length=1)
    paramname: constr(min_length=1)
    valuelist: Optional[Any] = None


class SearchParametersResponse(RootModel[List[SearchParametersResponseItem]]):
    root: List[SearchParametersResponseItem] = Field(..., min_length=1)


class VerifyAccount(BaseModel):
    clientid: Optional[str] = Field(
        None,
        description='Provide the client id that was created during the application registration process on Partners Portal.',
    )
    hmac: Optional[bytes] = Field(
        None,
        description='Provide SHA-256 encrypted value of the client secret, clientid and ts parameters above concatenated in this sequence (client secret, clientid, ts). The hmac parameter is used by DigiLocker to ensure the data integrity and authentication of the request. Use the Client Secret Key generated during the application registration process on Partners Portal as the client secret.',
    )
    mobile: Optional[int] = Field(
        None,
        description='This is the mobile number of the user. DigiLocker will check whether an account exists for this mobile number. Either uid or mobile is required to verify whether an account exists.',
    )
    ts: Optional[str] = Field(
        None,
        description='Provide a timestamp value in UNIX (or POSIX) format in IST time zone in seconds. This timestamp value must not be older than 30 minutes.',
    )
    uid: Optional[int] = Field(
        None,
        description='This is the Aadhaar number of the user. DigiLocker will check whether an account exists for this Aadhaar number. Either uid or mobile is required to verify whether an account exists.',
    )


class VerifyAccountResponse(BaseModel):
    digilockerid: str = Field(
        ...,
        description='A unique 36 character DigiLocker Id of the user account.',
        examples=['123e4567-e89b-12d3-a456-426655440000'],
    )
    registered: str = Field(
        ...,
        description='true indicates that the provided Aadhaar/mobile number is already registered and false indicates otherwise.',
        examples=['true'],
    )


class KeyInfo1(BaseModel):
    X509Data: Optional[Any] = None


class Signature1(BaseModel):
    KeyInfo: KeyInfo1
    SignatureValue: Optional[Any] = None
    SignedInfo: Optional[Any] = None


class XMLFormatSchema(BaseModel):
    CertificateData: List[Dict[str, Any]]
    Signature: Signature1


class Account1PushuriPostResponse(BaseModel):
    error: Optional[str] = Field(None, description='invalid_parameter')
    error_description: Optional[str] = Field(
        None,
        description='One or more of the mandatory parameters is missing or invalid. The error description text will contain one or more of the following error texts:|- \uf0b7 URI parameter is missing or invalid \uf0b7 Doctype parameter is missing or invalid \uf0b7 Description parameter is missing or invalid \uf0b7 Docid parameter is missing or invalid \uf0b7 Issuedate parameter is missing orinvalid \uf0b7 Timestamp parameter is missing or invalid \uf0b7 HMAC parameter is missing or invalid  \uf0b7 URI already exists in this account  \uf0b7 URI already exists in another account',
    )


class Account1PushuriPostResponse1(BaseModel):
    error: Optional[str] = Field(None, description='invalid_client_id')
    error_description: Optional[str] = Field(
        None, description='The client_id parameter is invalid'
    )


class Account1PushuriPostResponse2(BaseModel):
    error: Optional[str] = Field(None, description='invalid_digilocker_id')
    error_description: Optional[str] = Field(
        None, description='The digilockerid parameter is invalid'
    )


class Account1PushuriPostResponse3(BaseModel):
    error: Optional[str] = Field(None, description='unexpected_error')
    error_description: Optional[str] = Field(None, description='Internal server error')


class Account2VerifyPostResponse(BaseModel):
    error: Optional[Any] = Field(None, description='invalid_parameter')
    error_description: Optional[Any] = Field(
        None,
        description='One or more of the mandatory parameters is missing or invalid. The error description text will contain one or more of the following error texts:|- \uf0b7 Either one of uid or mobile number is mandatory \uf0b7 Timestamp parameter is missing or invalid \uf0b7 HMAC parameter is missing or invalid',
    )


class Account2VerifyPostResponse1(BaseModel):
    error: Optional[str] = Field(None, description='invalid_client_id')
    error_description: Optional[str] = Field(
        None, description='The client_id parameter is invalid'
    )


class Account2VerifyPostResponse2(BaseModel):
    error: Optional[Any] = Field(None, description='unexpected_error')
    error_description: Optional[Any] = Field(None, description='Internal server error')


class Parameter(Enum):
    Base64URL = 'Base64URL'
    SHA256 = 'SHA256'


class CodeChallenge(BaseModel):
    parameter: Optional[Parameter] = None


class Parameter1(Enum):
    S256 = 'S256'


class CodeChallengeMethod(BaseModel):
    parameter: Optional[Parameter1] = None


class Details4(BaseModel):
    access_token: str
    expires_in: int
    scope: str
    token_type: str


class Oauth21AuthorizeGetResponse(BaseModel):
    details: Optional[Details4] = None


class Parameter2(Enum):
    Base64URL = 'Base64URL'
    SHA256 = 'SHA256'


class CodeChallenge1(BaseModel):
    parameter: Optional[Parameter2] = None


class Parameter3(Enum):
    S256 = 'S256'


class CodeChallengeMethod1(BaseModel):
    parameter: Optional[Parameter3] = None


class Oauth21CodePostResponse(
    RootModel[Union[ResponseOne, ResponseTwo, ResponseThree, ResponseFour]]
):
    root: Union[ResponseOne, ResponseTwo, ResponseThree, ResponseFour]


class Oauth21CodePostResponse1(BaseModel):
    error: Optional[str] = Field(None, examples=['invalid_client_id'])
    error_description: Optional[str] = Field(
        None, examples=['The client_id parameter is invalid']
    )


class Oauth21CodePostResponse2(RootModel[Union[ResponseFive, ResponseSix]]):
    root: Union[ResponseFive, ResponseSix]


class Error(Enum):
    path_missing = 'path_missing'
    contenttype_missing = 'contenttype_missing'
    hmac_missing = 'hmac_missing'
    filename_missing = 'filename_missing'
    hmac_mismatch = 'hmac_mismatch'
    invalid_filename = 'invalid_filename'
    invalid_filesize = 'invalid_filesize'
    invalid_filetype = 'invalid_filetype'
    invalid_path = 'invalid_path'
    file_data_missing = 'file_data_missing'
    mimetype_mismatch = 'mimetype_mismatch'


class ErrorDescription(Enum):
    Path_parameter_is_missing = 'Path parameter is missing'
    Content_Type_parameter_is_missing = 'Content-Type parameter is missing'
    HMAC_parameter_is_missing = 'HMAC parameter is missing'
    Filename_is_missing_in_path_parameter = 'Filename is missing in path parameter'
    HMAC_does_not_match = 'HMAC does not match'
    Restricted_characters_are_not_allowed_in_file_name = (
        'Restricted characters are not allowed in file name'
    )
    The_file_size_exceeds_maximum_allowed_file_size_of_10MB = (
        'The file size exceeds maximum allowed file size of 10MB'
    )
    The_file_type_is_not_allowed = 'The file type is not allowed'
    The_destination_folder_does_not_exist = 'The destination folder does not exist'
    Missing_file_content_in_the_request = 'Missing file content in the request'
    The_mimetype_provided_in_Content_Type_parameter_does_not_match_with_the_mimetype_of_the_file = 'The mimetype provided in Content-Type parameter does not match with the mimetype of the file'


class Oauth21FileUploadPostResponse(BaseModel):
    error: Optional[Error] = None
    error_description: Optional[ErrorDescription] = None


class Oauth21FileUploadPostResponse1(BaseModel):
    error: Optional[str] = Field(None, examples=['invalid_token'])
    error_description: Optional[str] = Field(
        None, examples=['The access token is invalid']
    )


class Oauth21FileUploadPostResponse2(BaseModel):
    error: Optional[str] = Field(None, description='unexpected_error')
    error_description: Optional[str] = Field(None, description='Internal server error')


class Oauth21FileUriGetResponse(BaseModel):
    error: Optional[str] = Field(None, examples=['uri_missing'])
    error_description: Optional[str] = Field(None, examples=['URI parameter missing'])


class Oauth21FileUriGetResponse1(BaseModel):
    error: Optional[str] = Field(None, examples=['invalid_token'])
    error_description: Optional[str] = Field(
        None, examples=['The access token is invalid']
    )


class Oauth21FileUriGetResponse2(BaseModel):
    error: Optional[str] = Field(None, examples=['invalid_uri'])
    error_description: Optional[str] = Field(
        None, examples=['No file found for given URI']
    )


class Oauth21FileUriGetResponse3(
    RootModel[Union[Response3, Response4, Response5, Response6]]
):
    root: Union[Response3, Response4, Response5, Response6]


class Oauth21FileUriGetResponse4(RootModel[Union[Response1, Response2]]):
    root: Union[Response1, Response2]


class Item(BaseModel):
    date: constr(min_length=1)
    description: str
    id: constr(min_length=1) = Field(..., examples=[189079894])
    issuer: str
    mime: str
    name: constr(min_length=1)
    parent: constr(min_length=1)
    size: constr(min_length=1)
    type: constr(min_length=1)
    uri: str


class Oauth21FilesGetResponse(BaseModel):
    directory: constr(min_length=1)
    items: List[Item] = Field(..., min_length=1)


class Oauth21FilesGetResponse1(BaseModel):
    error: Optional[str] = Field(None, examples=['invalid_token'])
    error_description: Optional[str] = Field(
        None, examples=['The access token is invalid']
    )


class Oauth21FilesGetResponse2(BaseModel):
    error: Optional[str] = Field(None, examples=['invalid_id'])
    error_description: Optional[str] = Field(
        None, examples=['The folder does not exist']
    )


class Oauth21FilesGetResponse3(BaseModel):
    error: Optional[str] = Field(None, examples=['unexpected_error'])
    error_description: Optional[str] = Field(None, examples=['Internal server error'])


class Details5(BaseModel):
    date: str = Field(
        ...,
        description='This contains the date on which the certificate was last modified in DigiLocker.',
        examples=['2015-05-12T15:50:38Z'],
    )
    description: str = Field(
        ...,
        description='This is the descriptive document type stored in DigiLocker such as ‘Income Certificate’ or ‘Driving License’.',
        examples=['Class XII Marksheet'],
    )
    doctype: str = Field(
        ...,
        description='A 5 character unique document type provided by DigiLocker.',
        examples=['HSCER'],
    )
    issuer: str = Field(..., description='The name of the issuer.', examples=['CBSE'])
    issuerid: str = Field(
        ...,
        description='Unique DigiLocker issuer id as mentioned in the URI.',
        examples=['in.gov.cbse'],
    )
    mime: str = Field(
        ...,
        description='The list of mime types for the certificate data. This field will contain “application/PDF” or “application/xml”.',
        examples=['application/pdf'],
    )
    name: str = Field(
        ...,
        description='The name of the certificate.',
        examples=['Class XII Marksheet'],
    )
    parent: str = Field(..., description='This will be blank.', examples=[' '])
    size: str = Field(..., description='This will be blank.', examples=[' '])
    type: str = Field(..., description='String file.', examples=['file'])
    uri: str = Field(
        ...,
        description='This is the unique identifier of the document shared by the user in DigiLocker. You will use this identifier to get the actual file from DigiLocker using the API.',
        examples=['in.gov.cbse-HSCER-201412345678'],
    )


class Oauth21FilesIssuedGetResponse(BaseModel):
    details: Optional[Details5] = None


class Oauth21FilesIssuedGetResponse1(BaseModel):
    error: Optional[str] = Field(None, examples=['invalid_token'])
    error_description: Optional[str] = Field(
        None, examples=['The access token is invalid']
    )


class Oauth21FilesIssuedGetResponse2(RootModel[Union[ResponseSix, ResponseSeven]]):
    root: Union[ResponseSix, ResponseSeven]


class Details6(BaseModel):
    date: str = Field(
        ...,
        description='This contains the date of file upload in case of self uploaded documents',
        examples=['2015-05-12T15:50:38Z'],
    )
    description: str = Field(
        ...,
        description='This is the descriptive document type stored in DigiLocker such as ‘Income Certificate’ or ‘Driving License’.',
        examples=[''],
    )
    id: int = Field(
        ..., description='The id if this item is a folder.', examples=['5678']
    )
    issuer: str = Field(
        ...,
        description='The name of the issuer. This is blank in case of uploaded documents and folders.',
        examples=[''],
    )
    mime: str = Field(
        ...,
        description='The mime type of the file. This field will contain “application/PDF” for PDF files; “image/png” for PNG files and “image/jpg” or “image/jpeg” for JPG/JPEG files. This will be blank in case of folder.',
        examples=[''],
    )
    name: str = Field(
        ..., description='The name of the file or folder.', examples=['My Documents']
    )
    parent: str = Field(
        ..., description='The id of the parent folder.', examples=['1234']
    )
    size: str = Field(..., description='Size of file or folder.', examples=['366481'])
    type: str = Field(
        ...,
        description='String dir for folder and string file for file.',
        examples=['dir'],
    )
    uri: str = Field(
        ...,
        description='This is the unique identifier of the document shared by the user in DigiLocker. You will use this identifier to get the actual file from DigiLocker using the API. URI will be blank in case of folder.',
        examples=[''],
    )


class Oauth21FilesIdGetResponse(BaseModel):
    details: Optional[Details6] = None


class Oauth21FilesIdGetResponse1(BaseModel):
    error: Optional[str] = Field(None, examples=['invalid_token'])
    error_description: Optional[str] = Field(
        None, examples=['The access token is invalid']
    )


class Oauth21FilesIdGetResponse2(BaseModel):
    error: Optional[str] = Field(None, examples=['invalid_id'])
    error_description: Optional[str] = Field(
        None, examples=['The folder does not exist']
    )


class Oauth21FilesIdGetResponse3(BaseModel):
    error: Optional[str] = Field(None, examples=['unexpected_error'])
    error_description: Optional[str] = Field(None, examples=['Internal server error'])


class Oauth21PullDoctypePostResponse(BaseModel):
    error: Optional[Any] = Field(None, description='invalid_parameter')
    error_description: Optional[Any] = Field(
        None,
        description='One or more of the mandatory parameters is missing or invalid. The error description text will contain one or more of the following error texts:|- \uf0b7 The orgid parameter is missing or invalid \uf0b7 Timestamp parameter is missing or invalid \uf0b7 HMAC parameter is missing or invalid',
    )


class Oauth21PullDoctypePostResponse1(BaseModel):
    error: Optional[str] = Field(None, examples=['invalid_client_id'])
    error_description: Optional[str] = Field(
        None, examples=['The client_id parameter is invalid']
    )


class Oauth21PullDoctypePostResponse2(BaseModel):
    error: Optional[Any] = Field(None, description='unexpected_error')
    error_description: Optional[Any] = Field(None, description='Internal server error')


class Oauth21PullIssuersPostResponse(BaseModel):
    error: Optional[str] = Field(None, examples=['invalid_parameter'])
    error_description: Optional[str] = Field(
        None,
        examples=[
            'One or more of the mandatory parameters is missing or invalid. The error description text will contain one or more of the following error texts:|- \uf0b7 Timestamp parameter is missing or invalid \uf0b7 HMAC parameter is missing or invalid'
        ],
    )


class Oauth21PullIssuersPostResponse1(BaseModel):
    error: Optional[str] = Field(None, examples=['invalid_client_id'])
    error_description: Optional[str] = Field(
        None, examples=['The client_id parameter is invalid']
    )


class Oauth21PullIssuersPostResponse2(BaseModel):
    error: Optional[Any] = Field(None, description='unexpected_error')
    error_description: Optional[Any] = Field(None, description='Internal server error')


class Oauth21PullParametersPostResponse(BaseModel):
    error: Optional[Any] = Field(None, description='invalid_parameter')
    error_description: Optional[Any] = Field(
        None,
        description='One or more of the mandatory parameters is missing or invalid. The error description text will contain one or more of the following error texts:|- \uf0b7 The orgid parameter is missing or invalid \uf0b7 The doctype parameter is missing or invalid \uf0b7 Timestamp parameter is missing or invalid \uf0b7 HMAC parameter is missing or invalid',
    )


class Oauth21PullParametersPostResponse1(BaseModel):
    error: Optional[str] = Field(None, examples=['invalid_client_id'])
    error_description: Optional[str] = Field(
        None, examples=['The client_id parameter is invalid']
    )


class Oauth21PullParametersPostResponse2(BaseModel):
    error: Optional[Any] = Field(None, description='unexpected_error')
    error_description: Optional[Any] = Field(None, description='Internal server error')


class Details7(BaseModel):
    uri: str


class Oauth21PullPulldocumentPostResponse(BaseModel):
    details: Optional[Details7] = None


class Oauth21PullPulldocumentPostResponse1(RootModel[Union[Response13, ResponseSix]]):
    root: Union[Response13, ResponseSix]


class Oauth21PullPulldocumentPostResponse2(BaseModel):
    error: Optional[str] = Field(None, examples=['invalid_token'])
    error_description: Optional[str] = Field(
        None, examples=['The access token is invalid']
    )


class Oauth21PullPulldocumentPostResponse3(BaseModel):
    error: Optional[Any] = Field(None, description='record_not_found')
    error_description: Optional[Any] = Field(
        None,
        description='No record found in issuer database for given criteria. Please check the details and try again. If problem persists, see the FAQ section for possible causes.',
    )


class Oauth21PullPulldocumentPostResponse4(
    RootModel[Union[Response14, Response15, Response16, Response17, Response18]]
):
    root: Union[Response14, Response15, Response16, Response17, Response18]


class TokenTypeHint(Enum):
    refresh_token = 'refresh_token'
    access_token = 'access_token'


class Oauth21RevokePostRequest(BaseModel):
    token: str = Field(..., description='The token that needs to be revoked.')
    token_type_hint: Optional[TokenTypeHint] = Field(
        None,
        description='The type of the above token. The value will be one of access_token or refresh_token. If this parameter is not sent, DigiLocker will look for this token in both access and refresh tokens and then revoke it.',
    )


class Oauth21TokenPostRequest(BaseModel):
    Get_access_token_using_authorization_code: Optional[AccessToken] = Field(
        None, alias='Get access token using authorization code'
    )
    Get_access_token_using_device_code_and_OTP: Optional[DeviceAccessToken] = Field(
        None, alias='Get access token using device code and OTP'
    )
    Get_access_token_using_refresh_token: Optional[RefreshToken] = Field(
        None, alias='Get access token using refresh token'
    )


class Details8(BaseModel):
    digilockerid: str = Field(
        ...,
        description='A unique 36 character DigiLocker Id of the user account.',
        examples=['123e4567-e89b-12d3-a456-426655440000'],
    )
    dob: str = Field(
        ...,
        description='This is date of birth of the user as registered with DigiLocker in DDMMYYYY format.',
        examples=['31121970'],
    )
    eaadhar: Optional[Eaadhar] = Field(
        None,
        description='This indicates whether eAadhaar data is available for this account. Possible values are Y and N.',
    )
    gender: Gender = Field(
        ...,
        description='This is gender of the user as registered with DigiLocker. The possible values are M, F, T for male, female and transgender respectively.',
    )
    name: str = Field(
        ...,
        description='The name of the user as registered with DigiLocker.',
        examples=['Sunil Kumar'],
    )


class Oauth21UserGetResponse(BaseModel):
    details: Optional[Details8] = None


class Oauth21UserGetResponse1(BaseModel):
    error: Optional[str] = Field(None, examples=['invalid_token'])
    error_description: Optional[str] = Field(
        None, examples=['The access token is invalid']
    )


class Oauth21UserGetResponse2(BaseModel):
    error: Optional[str] = Field(None, examples=['unexpected_error'])
    error_description: Optional[str] = Field(None, examples=['Internal server error'])


class Oauth21XmlUriGetResponse(BaseModel):
    error: Optional[str] = Field(None, examples=['uri_missing'])
    error_description: Optional[str] = Field(None, examples=['URI parameter missing'])


class Oauth21XmlUriGetResponse1(BaseModel):
    error: Optional[str] = Field(None, examples=['invalid_token'])
    error_description: Optional[str] = Field(
        None, examples=['The access token is invalid']
    )


class Oauth21XmlUriGetResponse2(BaseModel):
    error: Optional[str] = Field(None, examples=['invalid_uri'])
    error_description: Optional[str] = Field(
        None, examples=['No file found for given URI']
    )


class Oauth21XmlUriGetResponse3(
    RootModel[Union[Response3, Response4, Response5, Response6]]
):
    root: Union[Response3, Response4, Response5, Response6]


class Oauth21XmlUriGetResponse4(RootModel[Union[Response1, Response2]]):
    root: Union[Response1, Response2]


class Item1(BaseModel):
    date: constr(min_length=1)
    description: constr(min_length=1)
    doctype: constr(min_length=1)
    issuer: constr(min_length=1)
    issuerid: constr(min_length=1)
    mime: Optional[List[Dict[str, Any]]] = None
    name: constr(min_length=1)
    parent: str
    size: str
    type: constr(min_length=1)
    uri: constr(min_length=1)


class Oauth22FilesIssuedGetResponse(BaseModel):
    items: List[Item1] = Field(..., min_length=1)
    resource: constr(min_length=1)


class Oauth22FilesIssuedGetResponse1(BaseModel):
    error: Optional[str] = Field(None, examples=['invalid_token'])
    error_description: Optional[str] = Field(
        None, examples=['The access token is invalid']
    )


class Oauth22FilesIssuedGetResponse2(RootModel[Union[ResponseSix, ResponseSeven]]):
    root: Union[ResponseSix, ResponseSeven]


class Oauth22XmlEaadhaarGetResponse(BaseModel):
    error: Optional[str] = Field(None, examples=['invalid token'])
    error_description: Optional[str] = Field(
        None, examples=['The access token is invalid']
    )


class Error1(Enum):
    aadhaar_not_linked = 'aadhaar_not_linked'
    aadhaar_not_available = 'aadhaar_not_available'


class ErrorDescription1(Enum):
    Aadhaar_is_not_linked_to_the_account = 'Aadhaar is not linked to the account'
    Aadhaar_data_is_not_available_for_this_user__Please_perform_Aadhaar_eKYC_again_ = 'Aadhaar data is not available for this user. Please perform Aadhaar eKYC again.'


class Oauth22XmlEaadhaarGetResponse1(BaseModel):
    error: Optional[Error1] = None
    error_description: Optional[ErrorDescription1] = None


class Oauth22XmlEaadhaarGetResponse2(
    RootModel[Union[Response3, Response4, Response5, Response6]]
):
    root: Union[Response3, Response4, Response5, Response6]


class Oauth22XmlEaadhaarGetResponse3(RootModel[Union[Response1, Response2]]):
    root: Union[Response1, Response2]


class Signup1DemoauthverifyPostResponse(
    RootModel[Union[Response7, Response8, Response9]]
):
    root: Union[Response7, Response8, Response9]


class Signup1DemoauthverifyPostResponse1(BaseModel):
    error: Optional[str] = Field(None, examples=['invalid_client_id'])
    error_description: Optional[str] = Field(
        None, examples=['The client_id parameter is invalid']
    )


class Signup1DemoauthverifyPostResponse2(BaseModel):
    error: Optional[Any] = Field(None, description='unexpected_error')
    error_description: Optional[Any] = Field(None, description='Internal server error')


class Signup2DemoauthPostResponse(RootModel[Union[Response10, Response11, Response12]]):
    root: Union[Response10, Response11, Response12]


class Signup2DemoauthPostResponse1(BaseModel):
    error: Optional[str] = Field(None, examples=['invalid_client_id'])
    error_description: Optional[str] = Field(
        None, examples=['The client_id parameter is invalid']
    )


class Signup2DemoauthPostResponse2(BaseModel):
    error: Optional[Any] = Field(None, description='unexpected_error')
    error_description: Optional[Any] = Field(None, description='Internal server error')


class Statistics1CountsPostResponse(BaseModel):
    error: Optional[str] = Field(None, description='invalid_parameter')
    error_description: Optional[str] = Field(
        None,
        description='One or more of the mandatory parameters is missing or invalid. The error description text will contain one or more of the following error texts:|- \uf0b7 Timestamp parameter is missing or invalid \uf0b7 HMAC parameter is missing or invalid',
    )


class Statistics1CountsPostResponse1(BaseModel):
    error: Optional[str] = Field(None, description='invalid_client_id')
    error_description: Optional[str] = Field(
        None, description='The client_id parameter is invalid'
    )


class Statistics1CountsPostResponse2(BaseModel):
    error: Optional[str] = Field(None, description='unexpected_error')
    error_description: Optional[str] = Field(None, description='Internal server error')
